/** Copy estilo Palace — bullets irreverentes por producto */
export const PALACE_COPY: Record<string, string[]> = {
  "gorra-desert-camo": [
    "CAMO DESERT CHOCOLATE CHIP. NO ES DEL EJÉRCITO — ES MEJOR.",
    "PARCHE ROSA Y AMARILLO. SE VE DESDE LEJOS.",
    "AJUSTABLE. CABE CASI EN TODAS LAS CABEZAS.",
    "COMPLEMENTO PERFECTO DEL DROP. PUNTO.",
  ],
  "star-tee-blanco": [
    "LOGO ROSA SALMÓN CON ESTRELLA. MINIMALISTA PERO NO ABURRIDO.",
    "BLANCO ÓPTICO. NO SE MANCHA... MENTIRA, SÍ SE MANCHA.",
    "HECHA EN L'HOSPITALET. ORGULLO LOCAL.",
    "LA CAMI QUE LLEVAS CUANDO QUIERES QUE SE VEA EL LOGO.",
  ],
  "hoods-chateau-tee": [
    "GRÁFICO YETI EN BUTACA ROJA. NO PREGUNTES POR QUÉ.",
    "OVERSIZE DE VERDAD — NO ES 'UN POQUITO GRANDE'.",
    "ESPALDA CON HOOD'S CHÂTEAU. LA GENTE TE SEGUIRÁ.",
    "VIENE EN CAJA DE COLECCIONISTA. SÍ, CAJA.",
  ],
  "logo-tee-negro": [
    "NEGRO. PARCHE AZUL EN PECHO. CERO RUIDO.",
    "PARCHE ICE UP! — NO ES UN STICKER DE TEMU.",
    "RELAXED FIT. PARA IR CÓMODO Y VERSE BIEN.",
    "MADE IN L'HOSPITALET. LO PONE EN LA ETIQUETA.",
  ],
  "logo-tee-crema": [
    "CREMA NEUTRA. PARCHE AZUL. COMBINA CON TODO.",
    "PIEZA ESENCIAL DEL DROP — NO ES FILLER.",
    "ALGODÓN PREMIUM. SE NOTA AL TOCARLA.",
    "FOTO EN HORMIGÓN. ESTÉTICA INDUSTRIAL.",
  ],
  "logo-tee-navy": [
    "NAVY OSCURO. PARCHE AZUL. DOBLE AZUL, DOBLE BIEN.",
    "LA CAMI PARA DÍAS GRIS — EN TODOS LOS SENTIDOS.",
    "MISMO PARCHE QUE LA CREMA Y LA NEGRA. FAMILIA.",
    "FOTOGRAFIADA SOBRE HORMIGÓN. SIN FILTROS.",
  ],
  "bolsa-ice-up": [
    "CAJA HOOD'S CHÂTEAU. CIELO, NUBES Y LADRILLO.",
    "PERFORADA PARA ABRIR COMO UN REGALO.",
    "INCLUIDA EN PEDIDOS SELECCIONADOS. NO SE VENDE SUELTA.",
    "OBJETO COLECCIONABLE. NO LA TIRES.",
  ],
};

export const TICKER_ITEMS = [
  "ICE UP!",
  "EDICIÓN LIMITADA",
  "HOOD'S CHÂTEAU",
  "DESERT CAMO",
  "DROP ACTIVO",
  "MADE IN L'HOSPITALET",
  "SIN STOCK MASIVO",
] as const;

export function getPalaceCopy(handle: string): string[] {
  return PALACE_COPY[handle] ?? [];
}
